services:

  queue:
    container_name: queue
    build:
      context: ./src/queue/
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "8007:15672"
    env_file:
      - .env
    
  queue-init:
    container_name: queue-init
    build:
      context: ./src/queue/config/
      dockerfile: Dockerfile
    depends_on:
      - queue
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: >
      sh -c "
      while ! curl -s http://queue:15672 > /dev/null; do
        echo 'Aguardando RabbitMQ...';
        sleep 2;
      done;
      python init.py
      "

  client:
    container_name: client
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    ports:
      - "8008:3000"
    depends_on:
      - queue-init

  report-db:
    container_name: report-db
    build:
      context: ./src/report/
      dockerfile: Dockerfile
    ports:
      - "5439:5432"
    env_file:
      - .env
    depends_on:
      - client
    volumes:
      - report_volume:/var/lib/postgresql/data


  classify-ai:
    container_name: classify-ai
    build:
      context: ./src/classify/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - report-db
      - queue
      - queue-init
    environment:
      - PYTHONUNBUFFERED=1
  feeling-ai:
    container_name: feeling-ai
    build:
      context: ./src/feeling/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - report-db
      - queue
      - queue-init
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  report_volume: