services:
  classify-ai:
    container_name: classify-ai
    build:
      context: ./src/classify/
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    env_file:
      - .env

  feeling-ai:
    container_name: feeling-ai
    build:
      context: ./src/feeling/
      dockerfile: Dockerfile
    ports:
      - "8006:8000"
    env_file:
      - .env

  client:
    container_name: client
    build:
      context: ./src/client/
      dockerfile: Dockerfile
    ports:
      - "8007:80"

  querue:
    container_name: queue
    build:
      context: ./src/queue/
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "8008:15672"
    env_file:
      - .env